<?xml version="1.0" encoding="utf-8"?><Database Name="synapsr" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=synapsr;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="synapsrConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.elevations" Member="elevations">
    <Type Name="elevation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ElevationName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="elevation_user" Member="users" ThisKey="Id" OtherKey="ElevationId" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IdSpecialitate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElevationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="avatar_uri" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="elevation_user" Member="elevation" ThisKey="ElevationId" OtherKey="Id" Type="elevation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="grupe_user" Member="grupe" ThisKey="GroupId" OtherKey="Id" Type="grupe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="specialitati_user" Member="specialitati" ThisKey="IdSpecialitate" OtherKey="Id" Type="specialitati" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.grupe" Member="grupes">
    <Type Name="grupe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="grupe_user" Member="users" ThisKey="Id" OtherKey="GroupId" Type="user" />
      <Association Name="grupe_reg_code" Member="reg_codes" ThisKey="Id" OtherKey="GroupId" Type="reg_code" />
    </Type>
  </Table>
  <Table Name="dbo.reg_codes" Member="reg_codes">
    <Type Name="reg_code">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="grupe_reg_code" Member="grupe" ThisKey="GroupId" OtherKey="Id" Type="grupe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.specialitati" Member="specialitatis">
    <Type Name="specialitati">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="specialitati_user" Member="users" ThisKey="Id" OtherKey="IdSpecialitate" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.teachers" Member="teachers">
    <Type Name="teacher">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>